server:
  port: 8002

spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/serverDrivenDB
    username: postgres
    password: root

  sql:
    init:
      mode: always

  jackson:
    default-property-inclusion: non_null



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.r2dbc: DEBUG

jwt:
  secret: my_super_secure_secret_key_123456789
  expiration: 86400000

