sonar.projectKey=user-service
sonar.projectName=User Service

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.host.url=http://localhost:9000
sonar.login=squ_83d8a3b35afd137bd1aec0360786728d7d144cbb